/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkflowRouteImport } from './routes/_authenticated/workflow'
import { Route as AuthenticatedSchemesRouteImport } from './routes/_authenticated/schemes'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPolicyRouteImport } from './routes/_authenticated/policy'
import { Route as AuthenticatedEligibilityRouteImport } from './routes/_authenticated/eligibility'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedEligibilityIndexRouteImport } from './routes/_authenticated/eligibility/index'
import { Route as AuthenticatedAdminVerificationRouteImport } from './routes/_authenticated/admin/verification'
import { Route as AuthenticatedAdminProvenanceRouteImport } from './routes/_authenticated/admin/provenance'
import { Route as AuthenticatedAdminIngestionRouteImport } from './routes/_authenticated/admin.ingestion'
import { Route as AuthenticatedAdminAiDiagnosticRouteImport } from './routes/_authenticated/admin/ai-diagnostic'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowRoute = AuthenticatedWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchemesRoute = AuthenticatedSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPolicyRoute = AuthenticatedPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEligibilityRoute =
  AuthenticatedEligibilityRouteImport.update({
    id: '/eligibility',
    path: '/eligibility',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEligibilityIndexRoute =
  AuthenticatedEligibilityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEligibilityRoute,
  } as any)
const AuthenticatedAdminVerificationRoute =
  AuthenticatedAdminVerificationRouteImport.update({
    id: '/admin/verification',
    path: '/admin/verification',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProvenanceRoute =
  AuthenticatedAdminProvenanceRouteImport.update({
    id: '/admin/provenance',
    path: '/admin/provenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIngestionRoute =
  AuthenticatedAdminIngestionRouteImport.update({
    id: '/admin/ingestion',
    path: '/admin/ingestion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAiDiagnosticRoute =
  AuthenticatedAdminAiDiagnosticRouteImport.update({
    id: '/admin/ai-diagnostic',
    path: '/admin/ai-diagnostic',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/eligibility': typeof AuthenticatedEligibilityRouteWithChildren
  '/policy': typeof AuthenticatedPolicyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/admin/ai-diagnostic': typeof AuthenticatedAdminAiDiagnosticRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/provenance': typeof AuthenticatedAdminProvenanceRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/eligibility/': typeof AuthenticatedEligibilityIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/policy': typeof AuthenticatedPolicyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/ai-diagnostic': typeof AuthenticatedAdminAiDiagnosticRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/provenance': typeof AuthenticatedAdminProvenanceRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/eligibility': typeof AuthenticatedEligibilityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/_authenticated/eligibility': typeof AuthenticatedEligibilityRouteWithChildren
  '/_authenticated/policy': typeof AuthenticatedPolicyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schemes': typeof AuthenticatedSchemesRoute
  '/_authenticated/workflow': typeof AuthenticatedWorkflowRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/ai-diagnostic': typeof AuthenticatedAdminAiDiagnosticRoute
  '/_authenticated/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/_authenticated/admin/provenance': typeof AuthenticatedAdminProvenanceRoute
  '/_authenticated/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/_authenticated/eligibility/': typeof AuthenticatedEligibilityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/applications'
    | '/copilot'
    | '/documents'
    | '/drafts'
    | '/eligibility'
    | '/policy'
    | '/profile'
    | '/schemes'
    | '/workflow'
    | '/admin/ai-diagnostic'
    | '/admin/ingestion'
    | '/admin/provenance'
    | '/admin/verification'
    | '/eligibility/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sitemap.xml'
    | '/applications'
    | '/copilot'
    | '/documents'
    | '/drafts'
    | '/policy'
    | '/profile'
    | '/schemes'
    | '/workflow'
    | '/'
    | '/admin/ai-diagnostic'
    | '/admin/ingestion'
    | '/admin/provenance'
    | '/admin/verification'
    | '/eligibility'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/applications'
    | '/_authenticated/copilot'
    | '/_authenticated/documents'
    | '/_authenticated/drafts'
    | '/_authenticated/eligibility'
    | '/_authenticated/policy'
    | '/_authenticated/profile'
    | '/_authenticated/schemes'
    | '/_authenticated/workflow'
    | '/_authenticated/'
    | '/_authenticated/admin/ai-diagnostic'
    | '/_authenticated/admin/ingestion'
    | '/_authenticated/admin/provenance'
    | '/_authenticated/admin/verification'
    | '/_authenticated/eligibility/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflow': {
      id: '/_authenticated/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthenticatedWorkflowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schemes': {
      id: '/_authenticated/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AuthenticatedSchemesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/policy': {
      id: '/_authenticated/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof AuthenticatedPolicyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eligibility': {
      id: '/_authenticated/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof AuthenticatedEligibilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eligibility/': {
      id: '/_authenticated/eligibility/'
      path: '/'
      fullPath: '/eligibility/'
      preLoaderRoute: typeof AuthenticatedEligibilityIndexRouteImport
      parentRoute: typeof AuthenticatedEligibilityRoute
    }
    '/_authenticated/admin/verification': {
      id: '/_authenticated/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AuthenticatedAdminVerificationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/provenance': {
      id: '/_authenticated/admin/provenance'
      path: '/admin/provenance'
      fullPath: '/admin/provenance'
      preLoaderRoute: typeof AuthenticatedAdminProvenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ingestion': {
      id: '/_authenticated/admin/ingestion'
      path: '/admin/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AuthenticatedAdminIngestionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ai-diagnostic': {
      id: '/_authenticated/admin/ai-diagnostic'
      path: '/admin/ai-diagnostic'
      fullPath: '/admin/ai-diagnostic'
      preLoaderRoute: typeof AuthenticatedAdminAiDiagnosticRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedEligibilityRouteChildren {
  AuthenticatedEligibilityIndexRoute: typeof AuthenticatedEligibilityIndexRoute
}

const AuthenticatedEligibilityRouteChildren: AuthenticatedEligibilityRouteChildren =
  {
    AuthenticatedEligibilityIndexRoute: AuthenticatedEligibilityIndexRoute,
  }

const AuthenticatedEligibilityRouteWithChildren =
  AuthenticatedEligibilityRoute._addFileChildren(
    AuthenticatedEligibilityRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedEligibilityRoute: typeof AuthenticatedEligibilityRouteWithChildren
  AuthenticatedPolicyRoute: typeof AuthenticatedPolicyRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchemesRoute: typeof AuthenticatedSchemesRoute
  AuthenticatedWorkflowRoute: typeof AuthenticatedWorkflowRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAiDiagnosticRoute: typeof AuthenticatedAdminAiDiagnosticRoute
  AuthenticatedAdminIngestionRoute: typeof AuthenticatedAdminIngestionRoute
  AuthenticatedAdminProvenanceRoute: typeof AuthenticatedAdminProvenanceRoute
  AuthenticatedAdminVerificationRoute: typeof AuthenticatedAdminVerificationRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedEligibilityRoute: AuthenticatedEligibilityRouteWithChildren,
  AuthenticatedPolicyRoute: AuthenticatedPolicyRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchemesRoute: AuthenticatedSchemesRoute,
  AuthenticatedWorkflowRoute: AuthenticatedWorkflowRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAiDiagnosticRoute: AuthenticatedAdminAiDiagnosticRoute,
  AuthenticatedAdminIngestionRoute: AuthenticatedAdminIngestionRoute,
  AuthenticatedAdminProvenanceRoute: AuthenticatedAdminProvenanceRoute,
  AuthenticatedAdminVerificationRoute: AuthenticatedAdminVerificationRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
